create table "next_auth"."feedbacks" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "name" text,
    "email" text,
    "emoji_name" text,
    "message" character varying,
    "emoji_code" text
);


alter table "next_auth"."feedbacks" enable row level security;

CREATE UNIQUE INDEX feedbacks_pkey ON next_auth.feedbacks USING btree (id);

alter table "next_auth"."feedbacks" add constraint "feedbacks_pkey" PRIMARY KEY using index "feedbacks_pkey";


