export const SEARCHQUERY = "SEARCHQUERY";
export const FETCHMOVIES = "FETCHMOVIES";
export const FETCHGENRES = "FETCHGENRES";
export const CURRENTPAGE = "CURRENTPAGE";
export const SELECTEDGENRE = "SELECTEDGENRE";
