export const SEARCHQUERY = "SEARCHQUERY";
export const FETCHMOVIES = "FETCHMOVIES";
export const FETCHGENRES = "FETCHGENRES";
export const CURRENTPAGE = "CURRENTPAGE";
export const CURRENTROUTE = "CURRENTROUTE";
export const SELECTEDGENRE = "SELECTEDGENRE";
export const SELECTEDCATEGORY = "SELECTEDCATEGORY";
export const GETCURRENTUSER = "GETCURRENTUSER";
