name: CI

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  workflow_dispatch:

jobs:
  # test:
  #   timeout-minutes: 5
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: '☁️ checkout repository'
  #       uses: actions/checkout@v2

  #     - name: '🔧 setup node'
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: '16.x'

  #     - name: '🔧 install pnpm@latest'
  #       run: npm i -g pnpm

  #     - name: '📦 Install dependencies'
  #       run: pnpm install

  #     - name: '🔧 Install Playwright Browsers'
  #       run: npx playwright install --with-deps

  #     - name: '🔍 Run Playwright tests'
  #       run: xvfb-run --auto-servernum -- pnpm test

  #     - uses: actions/upload-artifact@v3
  #       if: always()
  #       with:
  #         name: playwright-report
  #         path: playwright-report/
  #         retention-days: 30

  lint:
    name: Lint application
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: '☁️ checkout repository'
        uses: actions/checkout@v3

      - name: '🔧 setup node'
        uses: actions/setup-node@v3.5.1
        with:
          node-version: '16.x'

      - name: '🔧 install pnpm@latest'
        run: npm i -g pnpm

      - name: '📦 install dependencies'
        run: pnpm install

      - name: '🔍 lint code'
        run: pnpm lint

      - name: '📦 build application'
        run: pnpm build

  build:
    name: Build Repo Visualizer
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: '☁️ checkout repository'
        uses: actions/checkout@v3

      - name: '🔧 setup node'
        uses: actions/setup-node@v3.5.1
        with:
          node-version: '16.x'

      - name: '🔧 install pnpm@latest'
        run: npm i -g pnpm

      - name: '📦 install dependencies'
        run: pnpm install

      - name: '📊 repository visualizer'
        id: diagram
        uses: githubocto/repo-visualizer@0.8.2
        with:
          excluded_paths: 'node_modules,build,.vercel,.github,.husky'
          output_file: 'public/diagram.svg'
          should_push: false
          root_path: 'src/'

      - name: '📊 visualizer artifacts'
        uses: actions/upload-artifact@v2
        with:
          name: diagram
          path: public/diagram.svg
